### ISSUE TITLE
error Test the model

### ISSUE THREAD

**Issue by LeHoaiLinh278** [tamnguyenvan/age-gender-estimation#4]
when I'm run test_on_image.py with your pretrained model was output only value 'nan'

**Comment by tamnguyenvan** [comment]
HI, Can you share the command you used?

**Comment by LeHoaiLinh278** [comment]
> HI, Can you share the command you used?

python3 test_on_image.py --model_path 
age_gender_resnet18_v2_model.056.h5 --image_path input.jpg

**Comment by tamnguyenvan** [comment]
@LeHoaiLinh278 I have tested on Google Colab and didn't see any error. Can you create a google colab notebook and reproduce the error?
